name: Playwright Python Behave Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps

      - name: Run Behave tests
        run: |
          behave -f behave_html_formatter:HTMLFormatter -o reports/report.html

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: behave-report-${{ matrix.os }}
          path: reports/
